set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN T18 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property PACKAGE_PIN U16 [get_ports z]
set_property IOSTANDARD LVCMOS33 [get_ports z]


#set_property PACKAGE_PIN W5 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property PACKAGE_PIN R2 [get_ports rst]
#set_property IOSTANDARD LVCMOS33 [get_ports rst]
#set_property PACKAGE_PIN L1 [get_ports clk_out]
#set_property IOSTANDARD LVCMOS33 [get_ports clk_out]